USE retailcustomer
GO
CREATE OR ALTER PROCEDURE [dbo].[usp_InsertNewCustDbITEM]
@FileLoadId INT
AS
--[usp_InsertNewCustDbITEM] 3129
BEGIN
	MERGE INTO CUSTDB.ITEM a
	USING (SELECT S.*, D.DIVISION_ID, DP.DEPARTMENT_ID, C.CLASS_ID 
	 FROM ASO_STG.STAGE.STG_ITEM S LEFT JOIN STAGE.DIVISION D ON S.DIVISION=D.DIVISION_CD
	LEFT JOIN STAGE.DEPARTMENT DP ON S.DEPARTMENT=DP.DEPARTMENT_CD
	LEFT JOIN STAGE.CLASS C ON S.CLASS=C.CLASS_CD
	) b
	ON a.ITEM_ID = b.ITEM_ID
	WHEN MATCHED 
			AND (
				   a.[SKU_CD]	<>  b.[SKUCODE]
				OR a.[ITEM_DESC]	<> b.[ITEM_DESC]
				OR a.[STYLE_CD]	<> b.[STYLE_CODE]
				OR a.[STYLE_DESC]	<> b.[STYLE_DESC]
				OR a.[DMM] <>  b.[DMM]
				OR a.[BRAND]<> b.[BRAND]
				OR a.[PRIVATE_LABEL]<> b.[PRIVATE_LABEL]
				OR a.[PIM_PRODUCTNAME] <> b.[PIM_PRODUCTNAME]
				OR a.[DIVISION_ID]<>b.[DIVISION_ID]
				OR a.[DEPARTMENT_ID]<>b.[DEPARTMENT_ID]
				OR a.[CLASS_ID] <> b.[CLASS_ID]
			)
		THEN UPDATE SET 
			 a.[SKU_CD]=      b.[SKUCODE]
			,a.[ITEM_DESC]=      b.[ITEM_DESC]
			,a.[STYLE_CD]=      b.[STYLE_CODE]
			,a.[STYLE_DESC]=      b.[STYLE_DESC]
			,a.[DIVISION_ID]=     (SELECT DIVISION_ID FROM STAGE.DIVISION WHERE DIVISION_CD= b.[DIVISION])
			,a.[DEPARTMENT_ID]=      (SELECT DEPARTMENT_ID FROM STAGE.DEPARTMENT WHERE DEPARTMENT_CD= b.[DEPARTMENT]) 
			,a.[CLASS_ID]=      (SELECT CLASS_ID FROM STAGE.CLASS WHERE CLASS_CD=b.[CLASS])
			,a.[DMM]=      b.[DMM]
			,a.[BRAND]=      b.[BRAND]
			,a.[PRIVATE_LABEL]=      b.[PRIVATE_LABEL]
			,a.[FILEID]=      b.[FILEID]
			,a.[PIM_PRODUCTNAME]= b.[PIM_PRODUCTNAME]
	WHEN NOT MATCHED 
		THEN
			INSERT ([ITEM_ID],[SKU_CD],[ITEM_DESC],[STYLE_CD],[STYLE_DESC],[DIVISION_ID],[DEPARTMENT_ID]
				   ,[CLASS_ID],[DMM],[BRAND],[PRIVATE_LABEL],[FILEID],[PIM_PRODUCTNAME]) 
			VALUES (b.[ITEM_ID],b.[SKUCODE],b.[ITEM_DESC],b.[STYLE_CODE],b.[STYLE_DESC]
				,(SELECT DIVISION_ID FROM STAGE.DIVISION WHERE DIVISION_CD= b.[DIVISION])
				,(SELECT DEPARTMENT_ID FROM STAGE.DEPARTMENT WHERE DEPARTMENT_CD= b.[DEPARTMENT]) 
				,(SELECT CLASS_ID FROM STAGE.CLASS WHERE CLASS_CD=b.[CLASS])
				,b.[DMM],b.[BRAND],b.[PRIVATE_LABEL]
				,b.[FILEID],b.[PIM_PRODUCTNAME]);

		UPDATE ASO_STG.[STAGE].[ACADEMY_PROCESSED_FILES] 
		SET ISLOADCOMPLETE=1, LOADCOMPLETE_DATE=GETDATE() WHERE ID = @FileLoadId
END
